### ISSUE TITLE
Integrate old ES5 AngularJS app

### ISSUE THREAD

**Issue by valbuena-match** [CanopyTax/single-spa-angular1#35]
Hello,

First, I would like to thank you for this framework and all efforts you have made so far.

I have an old 1.4.x AngularJS application. The "app" is a JS file without the Angular lib.
I really read all the examples but as my app uses old ES5 (no imports), I don't know how to turn it into a microfront and exposing the configuration to register it (if possible without iFrames).

I would really appreciate your help.

Regards.

**Comment by joeldenning** [comment]
@valbuena-match great question!

Yes, you can totally do that. I created https://github.com/joeldenning/single-spa-es5-angularjs to show how. Let me know if you have any questions about how that is working! As part of it, I also just released [version 2.7.0](https://github.com/CanopyTax/single-spa-angular1/releases/tag/v2.7.0), which allows you to script tag single-spa-angular1 with `<script src="https://unpkg.com/single-spa-angular1"></script>`. Once you do that, you can use the library like this: `window.singleSpaAngular1.default(options)`.

Let me know if you have any further questions! Closing for now, but feel free to reopen with more discussion.

**Comment by iloughman** [comment]
Hi,

I'm trying to following the approach from the es5 angular example. Unfortunately, when I try to load this app I get an error that my application "does not export an unmount function or array of functions". What is the correct way to export the bootstrap, mount, and unmount functions in an es5 application using singleSpaAngular1.default.

**Comment by tarunnav** [comment]
> @valbuena-match great question!
> 
> Yes, you can totally do that. I created https://github.com/joeldenning/single-spa-es5-angularjs to show how. Let me know if you have any questions about how that is working! As part of it, I also just released [version 2.7.0](https://github.com/CanopyTax/single-spa-angular1/releases/tag/v2.7.0), which allows you to script tag single-spa-angular1 with `<script src="https://unpkg.com/single-spa-angular1"></script>`. Once you do that, you can use the library like this: `window.singleSpaAngular1.default(options)`.
> 
> Let me know if you have any further questions! Closing for now, but feel free to reopen with more discussion.

I tried your sample angularjs-es5 code, but I am getting below error
Application 'es5-app' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

How do I export  bootstrap, mount and unmount from my child app ?

**Comment by tarunnav** [comment]
> Hi,
> 
> I'm trying to following the approach from the es5 angular example. Unfortunately, when I try to load this app I get an error that my application "does not export an unmount function or array of functions". We are using SystemJS.import() to load the angular 1.x application. What is the correct way to export the bootstrap, mount, and unmount functions in an es5 application using singleSpaAngular1.default.

were you able to resolve your issue ? I want to know what is the solution

**Comment by nfours** [comment]
I am also having the same error.. I am trying to mount an angular 6 app but I am receiving following error.
"Uncaught Error: 'angular-app' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

**Comment by selnahal** [comment]
> I am also having the same error.. I am trying to mount an angular 6 app but I am receiving following error.
> "Uncaught Error: 'angular-app' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

were you able to solve this please? I'm getting the same error.

**Comment by nfours** [comment]
Do not know the exact reason why was that error happen to me. But after doing few changes in my web pack script I being able to mount it correctly. following is my webpack.config.js

const fs = require('fs');
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ProgressPlugin = require('webpack/lib/ProgressPlugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const rxPaths = require('rxjs/_esm5/path-mapping');
const autoprefixer = require('autoprefixer');
const postcssUrl = require('postcss-url');
const postcssImports = require('postcss-import');

const { NoEmitOnErrorsPlugin, SourceMapDevToolPlugin, NamedModulesPlugin } = require('webpack');
const {PostcssCliResources} = require ('@angular/cli')
const { BaseHrefWebpackPlugin } = require('base-href-webpack-plugin');
const AngularNamedLazyChunksWebpackPlugin = require('angular-named-lazy-chunks-webpack-plugin');
const { AngularCompilerPlugin } = require('@ngtools/webpack');

const nodeModules = path.join(process.cwd(), 'node_modules');
const realNodeModules = fs.realpathSync(nodeModules);
const genDirNodeModules = path.join(process.cwd(), 'src', '$$_gendir', 'node_modules');
const entryPoints = ["inline","polyfills","sw-register","styles","vendor","main"];
const hashFormat = {"chunk":"","extract":"","file":".[hash:20]","script":""};
const baseHref = "";
const deployUrl = "";
const projectRoot = process.cwd();
const maximumInlineSize = 10;

module.exports = {
  "resolve": {
    "extensions": [
      ".ts",
      ".js"
    ],
    "symlinks": true,
    "modules": [
      "./src",
      "./node_modules"
    ],
    "alias": rxPaths(),
    "mainFields": [
      "browser",
      "module",
      "main"
    ]
  },
  "resolveLoader": {
    "modules": [
      "./node_modules"
    ],
    "alias": rxPaths()
  },
  "entry": {
    "polyfills": [
      "./src/polyfills.ts"
    ],
    "styles": [
      "./src/styles/styles.scss"
    ],
    "main": [
      "./src/main.ts"
    ]
  },
  "output": {
    "path": path.join(process.cwd(), "dist"),
    "filename": "[name].bundle.js",
    "chunkFilename": "[id].chunk.js",
    "crossOriginLoading": false,
    "library": "angularApp",
    "libraryTarget": "window"

  },
  "module": {
    "rules": [
      {
        "test": /\.html$/,
        "loader": "raw-loader"
      },
      {
        "test": /\.(eot|svg|cur)$/,
        "loader": "file-loader",
        "options": {
          "name": "[name].[hash:20].[ext]",
          "limit": 10000
        }
      },
      {
        "test": /\.(jpg|png|webp|gif|otf|ttf|woff|woff2|ani)$/,
        "loader": "url-loader",
        "options": {
          "name": "[name].[hash:20].[ext]",
          "limit": 10000
        }
      },
	  {
		"exclude": [
          path.join(process.cwd(), "src/styles.css")
        ],
		//include: [path.join(process.cwd(), "src/styles")],  
		test: /\.(scss|sass)$/,
		use: [
			'css-to-string-loader',
			'style-loader',
			{ 
				loader: 'css-loader', 
				options: { 
					sourceMap: true 
				} 
			},
			{ 
				loader: 'sass-loader', 
				options: { 
					sourceMap: true 
				} 
			}
		]
	  },
      {
        "test": /\.ts$/,
        "loader": "@ngtools/webpack"
      }
    ]
  },
  "plugins": [
    new NoEmitOnErrorsPlugin(),
    new CopyWebpackPlugin([
      {
        "context": "src",
        "to": "",
        "from": {
          "glob": "assets/**/*",
          "dot": true
        }
      },
      {
        "context": "src",
        "to": "",
        "from": {
          "glob": "favicon.ico",
          "dot": true
        }
      }
    ], {
      "ignore": [
        ".gitkeep",
        "**/.DS_Store",
        "**/Thumbs.db"
      ],
      "debug": "warning"
    }),
    new ProgressPlugin(),
    new CircularDependencyPlugin({
      "exclude": /(\\|\/)node_modules(\\|\/)/,
      "failOnError": false,
      "onDetected": false,
      "cwd": projectRoot
    }),
    new AngularNamedLazyChunksWebpackPlugin(),
	new CleanWebpackPlugin(
		{
			root: path.join(process.cwd(), "dist"),
			verbose: true
		}
	),	
    new HtmlWebpackPlugin({
      "template": "./src/index.html",
      "filename": "./index.html",
      "hash": false,
      "inject": true,
      "compile": true,
      "favicon": false,
      "minify": false,
      "cache": true,
      "showErrors": true,
      "chunks": "all",
      "excludeChunks": [],
      "title": "Webpack App",
      "xhtml": true,
      "chunksSortMode": function sort(left, right) {
        let leftIndex = entryPoints.indexOf(left.names[0]);
        let rightIndex = entryPoints.indexOf(right.names[0]);
        if (leftIndex > rightIndex) {
            return 1;
        }
        else if (leftIndex < rightIndex) {
            return -1;
        }
        else {
            return 0;
        }
    }
    }),
	new BaseHrefWebpackPlugin({ baseHref: 'http://localhost:3004/' }),
    new SourceMapDevToolPlugin({
      "filename": "[file].map[query]",
      "moduleFilenameTemplate": "[resource-path]",
      "fallbackModuleFilenameTemplate": "[resource-path]?[hash]",
      "sourceRoot": "webpack:///"
    }),
    new NamedModulesPlugin({}),
    new AngularCompilerPlugin({
      "mainPath": "main.ts",
      "platform": 0,
      "hostReplacementPaths": {
        "environments/environment.ts": "environments/environment.ts"
      },
      "sourceMap": true,
      "tsConfigPath": "src/tsconfig.app.json",
      "skipCodeGeneration": true,
      "compilerOptions": {}
    })
  ],
  optimization: {
	splitChunks: {
	  cacheGroups: {
		vendor: {
		  name: 'vendor',
		  chunks: chunk => chunk.name == 'main',
		  reuseExistingChunk: true,
		  priority: 1,
		  test: module =>
			/[\\/]node_modules[\\/]/.test(module.context),
		  minChunks: 1,
		  minSize: 0
		},
		inline:{
		  name: 'inline',
		  chunks: chunk => chunk.name == 'inline',
		  reuseExistingChunk: true,
		  minChunks: 1
			
		}
	  }
	}
  },		
  
  "node": {
    "fs": "empty",
    "global": true,
    "crypto": "empty",
    "tls": "empty",
    "net": "empty",
    "process": true,
    "module": false,
    "clearImmediate": false,
    "setImmediate": false
  },
  "devServer": {
    "historyApiFallback": true
  }
};

**Comment by zengyunchun** [comment]
@joeldenning hello, I notice [qiankun](https://github.com/umijs/qiankun)  micorfontend is based on single-spa, but qiankun could not integrate old ES5 Angularjs app, i want to bundle the qiankun es6 module to a script tag like your single-spa-angular1 and use in a global variable, can you  teach me how to do this, thanks a lot!!

**Comment by joeldenning** [comment]
Hi @zengyunchun - could you create a new github issue for this? It will be easier to track as a new issue.
